### ISSUE TITLE
Bad version in npm package

### ISSUE THREAD

**Issue by iasinDev** [mistic100/angular-jqcloud#10]
Hi, 

I was trying to install the package by putting in my bower.json: "angular-jqcloud": "~1.0.1"

but after executing npm install I get:

![screenshot002](https://cloud.githubusercontent.com/assets/12020079/9090570/4a04bc64-3b9b-11e5-9c95-4d2456016507.jpg)

And accordingly to this, I get the code of 1.0.0 version that get me errors on execution refering  $elem.jQCloud that I can see in the GitHub version that it's ok to  jQuery($elem) ( angular-jqcloud/angular-jqcloud.js)

So I think that somehow the npm package it's "corrupted" the line "version": "1.0.0", cause it's different from the one of GitHub "version": "1.0.1", cause this problems...

Please could you check it?

many many thanks in advance

**Comment by mistic100** [comment]
Why are you talking about NPM ? the plugin is not published on npm repository, only Bower.

The bower file was just never updated, will publish 1.0.2

**Comment by iasinDev** [comment]
Oh yes sorry, I'm a little bit newby on this, and I have mixed the concept/names...
I execute npm command but finally it executes my bower.json getting this package...

Great! I'll use it as soon as ready, thank you very much! :-)
