### ISSUE TITLE
Problem with injecting angular-jqcloud into app.module

### ISSUE THREAD

**Issue by bbaki** [mistic100/angular-jqcloud#12]
Hej, how am I supposed to inject jqcloud into my app as a dependency? I'm doing this:
>var app = angular
>    .module('app', [
>    'angular-jqcloud'
> ]);

I have both the js and css file loaded correctly (chrome network says so). After adding the injection I get the following error:
>Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
>Error: [$injector:modulerr] Failed to instantiate module angular-jqcloud due to:
>Error: [$injector:nomod] Module 'angular-jqcloud' is not available! You either misspelled the module >name or forgot to load it. If registering a module ensure that you specify the dependencies as the >second argument.

Thanks in advance.

**Comment by mistic100** [comment]
are you sure you load the plugin before your app ?

otherwise, provide a live example, I can't help with such info

**Comment by bbaki** [comment]
Thanks for the fast response. Yes I'm pretty sure of it, I've tried to place the app in a few places but I still get the same result. I will supply a live example tomorrow.

**Comment by bbaki** [comment]
I got a plunker live example, open up the console to see the error. angular.module works fine when you comment out 'angular-jqcloud'. 
http://plnkr.co/edit/wgnEaePE9gR6QHmvZEcE?p=preview

**Comment by mistic100** [comment]
?????????

where is the plugin file ?
https://github.com/mistic100/angular-jqcloud/blob/master/angular-jqcloud.js

**Comment by bbaki** [comment]
Ok, I knew it was something stupid. I didn't notice it among all those readme, licence files. The source file is normally in some sort of folder, my bad. Works now, thanks for the help :)
