### ISSUE TITLE
Cannot read property 'defaults' of undefined

### ISSUE THREAD

**Issue by nolines** [mistic100/angular-jqcloud#14]
defaults throws an error at example codebase.

**Comment by mistic100** [comment]
what ? could you explain what you do what you get ?
I'm not god i don't read in your mind (and I don't help people who don't take the time to setup an example)

**Comment by nolines** [comment]
it causes from my lazy load. not fault of your repo calm down a bit.

**Comment by frengom** [comment]
@nolines I have the same problem, how did you fix? Thanks for your help.

**Comment by kristof-mattei** [comment]
Don't just load `bower_components/angular-jqcloud/angular-jqcloud.js`, load `bower_components/jqcloud2/dist/jqcloud.js` FIRST.
