### ISSUE TITLE
can't assign scope variables directly to attributes

### ISSUE THREAD

**Issue by gaurav5430** [mistic100/angular-jqcloud#17]
For example, i need to specify **colors='["#00ff00", "#00e500", "#00cc00", "#00b200", "#009900", "#007f00", "#006600", "#004c00", "#003300"]'**

instead of **colors='colorsArr'** , where **$scope.colorsArr = ["#00ff00", "#00e500", "#00cc00", "#00b200", "#009900", "#007f00", "#006600", "#004c00", "#003300"]**

**Comment by mistic100** [comment]
colors="{{colorsArr}}" I guess.
Basic Angular :-)

**Comment by mistic100** [comment]
And it's in the example file..

**Comment by gaurav5430** [comment]
my bad. 
was trying to assign a variable as we do in ng-if/ng-show etc. 
Should have known that we can assign an expression.
