### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by nguillaumin** [mistic100/angular-jqcloud#18]
Hi,

Any chance your package could be published in NPM in addition to Bower?

That would be useful when not using Bower (e.g. NPM only, or other package managers like [JSPM](http://jspm.io/)). That's especially relevant with newer toolchains like Typescript, ES6, SystemJS, etc. which are moving away from Bower in favour of module systems...

Cheers,

Nicolas

**Comment by chiptus** [comment]
+1

**Comment by chiptus** [comment]
You can install by using "npm i mistic100/angular-jqcloud -S"
but there's another problem that the package.json require jqcloud2 which is not an npm package

**Comment by nguillaumin** [comment]
Good point, raised https://github.com/mistic100/jQCloud/issues/16

**Comment by mistic100** [comment]
https://www.npmjs.com/package/angular-jqcloud
