### ISSUE TITLE
Problem with injecting angular-jqcloud into angular Project

### ISSUE THREAD

**Issue by medamineosm** [mistic100/angular-jqcloud#20]
Project Structure
<img width="176" alt="image" src="https://user-images.githubusercontent.com/5613773/28774748-2aea04de-75ef-11e7-8709-2a05137f4407.png">
index.html 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/5613773/28774777-4d67f386-75ef-11e7-895d-9d3af8fe11c9.png">
app.js
<img width="299" alt="image" src="https://user-images.githubusercontent.com/5613773/28774801-652a151c-75ef-11e7-9e2b-93ac95c8e768.png">
view3.js
<img width="297" alt="image" src="https://user-images.githubusercontent.com/5613773/28774819-7197c07e-75ef-11e7-885e-cf5cb982602b.png">
bower.js
<img width="224" alt="image" src="https://user-images.githubusercontent.com/5613773/28774852-87f59706-75ef-11e7-8ba1-bacf39f78f76.png">
The http load files
<img width="250" alt="image" src="https://user-images.githubusercontent.com/5613773/28774887-afc613dc-75ef-11e7-8de5-4175b6874970.png">
The error
<img width="250" alt="image" src="https://user-images.githubusercontent.com/5613773/28774874-9f5b9a4e-75ef-11e7-88bf-e4c0f3a30560.png">

**Comment by mistic100** [comment]
Why angular jqcloud is not a bower package ? Do you have jquery ?

**Comment by medamineosm** [comment]
Normally i installed jqcloud by bower and doesn't work and i tried with the manually installation yes i have Jquery
![image](https://user-images.githubusercontent.com/5613773/28779654-460149c0-7604-11e7-834b-4e4691c964d6.png)
Index.html
![image](https://user-images.githubusercontent.com/5613773/28779680-556ca4ae-7604-11e7-8da1-0acdfd107cf3.png)
(i can upload it github if you want on )

**Comment by medamineosm** [comment]
https://github.com/medamineosm/Angular-JQcloud-Project

**Comment by mistic100** [comment]
You are loading angular-jqcloud before angular !!

**Comment by medamineosm** [comment]
Thank you very much.
