### ISSUE TITLE
How can we change color or size using the angular Example

### ISSUE THREAD

**Issue by medamineosm** [mistic100/angular-jqcloud#21]
view1.js
![image](https://user-images.githubusercontent.com/5613773/28815871-225c8210-76a3-11e7-9d88-4d6cffe31384.png)
view.html
![image](https://user-images.githubusercontent.com/5613773/28815897-34cf3a14-76a3-11e7-91e6-99d87fbc1460.png)

**Comment by mistic100** [comment]
What do you want exactly ?

- Change the color of each word individually ?
Use a CSS class via the `html` property http://mistic100.github.io/jQCloud/#words-options

- Change the cloud options ?
Every cloud options http://mistic100.github.io/jQCloud/#cloud-options is settable with an attribute.
This is in the example https://github.com/mistic100/angular-jqcloud/blob/master/examples/index.html

```html
<jqcloud colors="{{colors}}" font-size="{from:0.09, to:0.04}"></jqcloud>
```
```js
$scope.colors = ['red', 'blue'];
```

**Comment by medamineosm** [comment]
Thank you a lot this is exactly what i want thank you very helpful
