### ISSUE TITLE
Cannot get angular directive to work

### ISSUE THREAD

**Issue by kalkrishnan** [mistic100/angular-jqcloud#5]
It is not able to pickup JQCloud as a valid dependency. My bower.json is as below:

{
  "name": "phat-stats-front-end",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.3.0",
    "json3": "^3.3.0",
    "es5-shim": "^4.0.0",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.3.0",
    "angular-cookies": "^1.3.0",
    "angular-resource": "^1.3.0",
    "angular-route": "^1.3.0",
    "angular-sanitize": "^1.3.0",
    "angular-touch": "^1.3.0",
    "jqcloud2": "git://github.com/mistic100/jQCloud.git#2.0.1"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.0",
    "angular-scenario": "~1.3.0"
  },
  
  "appPath": "app"
}

It still gives me the below error:

 TypeError: undefined is not a function
    at link (http://localhost:9000/scripts/angular-jqcloud.js:37:13)

at this line:

      $elem.jQCloud($scope.words, options);

Not sure what I am doing wrong.

**Comment by mistic100** [comment]
I don't see "angular-jqcloud" in your bower file....
and as "jqcloud2" is a dependency of "angular-jqcloud" you don't need to redefine it

**Comment by kalkrishnan** [comment]
Sorry, newbie with angular so was figuring things out. I have included angular-jqcloud as a dependency in my app:

angular.module('PhatStatsApp.controllers', ['angular-jqcloud']).

and in the angular-jqcloud module, all of the below show valid values:

        console.log($scope.words);
		  console.log($elem);
		  console.log(options);
but the line directly below them, errors out:

  $elem.jQCloud($scope.words, options);

with TypeError: undefined is not a function.  Not sure why this is going on. If I use jQCloud as not an angular module, it works fine.

**Comment by kalkrishnan** [comment]
Had to replace $elem with $(elem) and it works now, thanks

**Comment by mistic100** [comment]
angular docs says about `link`
>element is the jqLite-wrapped element that this directive matches.

so it should already be a jQuery object, did I miss something ?

**Comment by almcewen** [comment]
I had the same problem. I made the following mod and it worked:
```
$elem.jQCloud($scope.words, options);
```
to
```
 $elem = $($elem).jQCloud($scope.words, options);
```

I logged $elem before and after the change and it looked like this:
![screen shot 2015-04-09 at 1 45 55 pm](https://cloud.githubusercontent.com/assets/5035612/7065295/d8b4f0f8-debe-11e4-962c-fe16e6896eda.png)
