### ISSUE TITLE
Possible to push items to words array without redraw? 

### ISSUE THREAD

**Issue by jforaker** [mistic100/angular-jqcloud#6]
I would like to use this for dynamic content. Think of a live chat where current usernames are in the word cloud (as they join the room, they appear in the word cloud).

It works nicely, however when I push a username into the words array, the cloud redraws and changes the color of each username. It would be cool to have a "cache" feature or something similar where current words in the array are not redrawn.  Bonus if you add subtle animations when a new word enters.  Let me know, thanks!

**Comment by mistic100** [comment]
This question should be in jQCloud repo, not here.

And don't expect any update from myself, I'll accept PRs but I don't touch the code.
